package constants

// List of error codes returned by the server in the failed responses body
const (
	SUCCESS = "ACC-000"

	VAL_MISSING_FIRST_NAME = "VAL-001"
	VAL_MISSING_LAST_NAME  = "VAL-002"
	VAL_MISSING_EMAIL      = "VAL-003"
	VAL_MISSING_PASSWORD   = "VAL-004"

	VAL_INVALID_FIRST_NAME = "VAL-011"
	VAL_INVALID_LAST_NAME  = "VAL-012"
	VAL_INVALID_EMAIL      = "VAL-013"
	VAL_INVALID_PASSWORD   = "VAL-014"

	VAL_EMAIL_ALREADY_EXISTS = "VAL-023"

	REQ_JSON_BIND = "REQ-001"

	DATABASE_ERROR = "DB-001"

	AUTH_INVALID_EMAIL    = "AUTH-001"
	AUTH_INVALID_PASSWORD = "AUTH-002"

	AUTH_JWT_FAILURE = "AUTH-011"
	AUTH_JWT_MISSING = "AUTH-012"
	AUTH_JWT_INVALID = "AUTH-013"
	AUTH_JWT_EXPIRED = "AUTH-014"
)
